const DESCRIPTIONS = {
  'signal-flow': 'Der Signalweg bündelt Geräte, Eingangs- und Ausgangspegel sowie den Dry/Wet-Mix.', input: 'Wählt den Audioeingang und stellt dessen Pegel vor dem Processing ein.', output: 'Wählt den Audioausgang und stellt den finalen Ausgangspegel ein.', mix: 'Mischt unbearbeitetes und bearbeitetes Signal. Wet Gain und Auto Gain wirken nur auf den Wet-Pfad.', presets: 'Speichert und lädt komplette Klang- und Steuerzustände.', snapshots: 'Vergleicht zwei Zustände und überblendet sie per Morph-Regler.', macros: 'Bündelt mehrere Parameter auf acht schnell bedienbare Makros.', modulation: 'LFOs und Envelope Follower bewegen zugewiesene Parameter um ihren Grundwert.', 'modulation-matrix': 'Verbindet eine Modulationsquelle mit einem Zielparameter und bestimmt Stärke sowie Richtung.', 'macro-assignments': 'Legt pro Makro Zielparameter und Wertebereich fest.', performance: 'Bietet schnellen Zugriff auf ausgewählte Performance-Funktionen.', processing: 'Die Module bearbeiten das Signal in der hier gezeigten Reihenfolge.', levels: 'Zeigt den aktuellen Eingangs- und Ausgangspegel. Die Buttons öffnen die beiden Analyzer.',
  freeze: 'Free wiederholt einen frei gewählten vorherigen Abschnitt. Sync richtet die Länge an erkanntem oder manuellem Tempo aus.', gate: 'Gate schließt leise Signale; Expander senkt sie abgestuft ab. Beides reduziert Rauschen und schafft mehr Dynamik.', transient: 'Verstärkt oder schwächt Attack und Sustain, ohne die Grundlautstärke gezielt zu komprimieren.', drive: 'Mischt die charaktereigene Sättigung dosiert zu. Tone formt die Höhen, Bias die Symmetrie und Shape die Härte der Kennlinie.', wavefolder: 'Faltet die Wellenform bei höherem Pegel und erzeugt zusätzliche Obertöne.', crusher: 'Reduziert Bit-Tiefe und/oder Sample-Rate für digitale, körnige Klangfarben.', filter: 'Formt den Frequenzbereich. Filtertyp, Cutoff und Resonance bestimmen, welche Bereiche betont oder gedämpft werden.', eq: 'Hebt oder senkt Frequenzbereiche. Shelf, Tone, Tilt und Graphic EQ haben unterschiedliche Klangformungen.', compressor: 'Verringert Pegelunterschiede oberhalb des Thresholds und kann mit Makeup Gain ausgeglichen werden.', width: 'Verändert das Verhältnis von Mitten- und Seitensignal – von Mono bis breiter Stereoabbildung.', clipper: 'Soft Clipper rundet Peaks weich ab und färbt mit Obertönen. Limiter reduziert Peaks oberhalb des Thresholds für Pegelkontrolle.',
  lfo1: 'LFO 1 erzeugt eine wiederkehrende Modulation mit wählbarer Wellenform, Rate, Tiefe und Phase.', lfo2: 'LFO 2 ist unabhängig von LFO 1 und kann eigene Ziele sowie Einstellungen steuern.', envelope1: 'Envelope Follower 1 folgt dem Eingangssignal. Attack und Release bestimmen, wie schnell die Modulation reagiert.', envelope2: 'Envelope Follower 2 arbeitet unabhängig und kann mit anderen Zeiten oder Zielen parallel folgen.'
};
const keyFor = element => element.dataset.collapseSection || (element.dataset.collapsible ? element.dataset.collapsible : null);
const help = text => { const element = document.createElement('span'); element.className = 'component-help'; element.tabIndex = 0; element.setAttribute('role', 'img'); element.setAttribute('aria-label', 'Info: ' + text); element.innerHTML = '<span aria-hidden="true">i</span><span class="component-tooltip" role="tooltip"></span>'; element.querySelector('.component-tooltip').textContent = text; return element; };
export function addComponentTooltips(root = document) {
  for (const element of root.querySelectorAll('[data-collapse-section], [data-collapsible], .modulation-module')) {
    const inferred = keyFor(element) || (element.querySelector('h3')?.textContent.includes('LFO 1') ? 'lfo1' : element.querySelector('h3')?.textContent.includes('LFO 2') ? 'lfo2' : element.querySelector('h3')?.textContent.includes('Envelope Follower 1') ? 'envelope1' : element.querySelector('h3')?.textContent.includes('Envelope Follower 2') ? 'envelope2' : null);
    const text = DESCRIPTIONS[inferred]; if (!text || element.querySelector(':scope .component-help')) continue;
    const title = element.querySelector(':scope > .panel-title > h2, :scope > .subsection-header > h3, :scope > .module-header > h3, :scope > .module-header > .module-toggle > span:first-child');
    if (title) title.after(help(text));
  }
}
