import { ANALYZER_DEFAULT_SOURCES, ANALYZER_SOURCE_LABELS } from '../audio/AnalyzerSources.js';
import { filterResponseAt } from './FilterResponseVisualization.js';
import { eqResponseAt } from './EQResponseVisualization.js';

const clamp = (value, min, max) => Math.min(max, Math.max(min, value));
const STATE_PREFIX = 'syntakt-analyzer-state-v3-';
const SOURCE_LABELS = ANALYZER_SOURCE_LABELS;
const VIEW_INFO = {
  waveform: 'Zeitbereich der gewählten Analyzer-Abgriffe', spectrum: 'Spektrum der gewählten Analyzer-Abgriffe',
  spectrogram: 'Laufendes Spektrogramm der ersten sichtbaren Source', dynamics: 'Peak, RMS und Crest Factor',
  gainReduction: 'Tatsächliche Gain Reduction des gewählten Prozessors', response: 'Live-Spektrum mit Filter- und EQ-Kennlinien',
  transient: 'Signal- und Envelope-Verlauf'
};
const DEFAULT_SOURCES = ANALYZER_DEFAULT_SOURCES;
const readState = id => { try { const state = JSON.parse(localStorage.getItem(STATE_PREFIX + id) || '{}'); return state && typeof state === 'object' ? state : {}; } catch { return {}; } };
const colors = () => { const style = getComputedStyle(document.documentElement); return [1, 2, 3, 4, 5, 6].map(index => style.getPropertyValue('--analyzer-' + index).trim() || ['#73a9c9', '#d29a6a', '#7fba9b', '#ba88b5', '#b7ad69', '#9b9fb7'][index - 1]); };
const css = name => getComputedStyle(document.documentElement).getPropertyValue(name).trim();
const hexRgb = color => { const text = color.replace('#', ''); return /^[0-9a-f]{6}$/i.test(text) ? [0, 2, 4].map(index => parseInt(text.slice(index, index + 2), 16)) : [100, 170, 200]; };
const db = value => 20 * Math.log10(Math.max(value, .000001));

export class VisualizationPanel {
  constructor(canvas, selector, description, controls = {}) {
    this.canvas = canvas; this.context = canvas.getContext('2d'); this.selector = selector; this.description = description;
    this.panel = controls.panel || canvas.closest('.floating-analyzer'); this.id = controls.analyzerId || this.panel?.dataset.analyzerId || '1';
    this.events = new AbortController(); this.paused = false; this.lastAnalysis = null; this.settings = null; this.metrics = { compressor: 0, limiter: 0 }; this.modulation = null;
    this.history = { spectrogram: [], peak: [], rms: [], reduction: [], input: [], envelope1: [], envelope2: [] };
    this.sourceNames = Object.keys(SOURCE_LABELS); this.state = this.loadState(); this.mode = this.state.mode;
    this.buildSourceControls(); this.bind(); this.resize(); this.setMode(this.mode); this.render(null);
  }
  loadState() { const stored = readState(this.id), sources = Array.isArray(stored.sources) ? stored.sources : [], visible = Array.isArray(stored.visible) ? stored.visible : []; return { mode: VIEW_INFO[stored.mode] ? stored.mode : 'spectrum', sources: Array.from({ length: 6 }, (_, index) => sources[index] || DEFAULT_SOURCES[index] || 'output'), visible: Array.from({ length: 6 }, (_, index) => visible[index] !== false), reductionTarget: stored.reductionTarget === 'limiter' ? 'limiter' : 'compressor', envelopeTarget: stored.envelopeTarget === 'envelope2' ? 'envelope2' : 'envelope1' }; }
  saveState() { try { localStorage.setItem(STATE_PREFIX + this.id, JSON.stringify(this.state)); } catch {} }
  bind() { this.selector.addEventListener('change', event => this.setMode(event.target.value), { signal: this.events.signal }); this.pauseButton?.addEventListener('click', () => this.setPaused(!this.paused), { signal: this.events.signal }); window.addEventListener('resize', () => { if (!this.paused && !this.panel?.classList.contains('is-hidden')) this.render(this.lastAnalysis); }, { signal: this.events.signal }); if ('ResizeObserver' in window) { this.resizeObserver = new ResizeObserver(() => { if (!this.paused && !this.panel?.classList.contains('is-hidden')) this.render(this.lastAnalysis); }); this.resizeObserver.observe(this.canvas); } }
  buildSourceControls() {
    this.sourceArea = this.panel?.querySelector('.analyzer-source-area'); this.pauseButton = this.panel?.querySelector('[data-analyzer-pause]'); if (!this.sourceArea) return;
    this.sourceArea.replaceChildren(); this.slots = this.state.sources.map((source, index) => { const row = document.createElement('label'); row.className = 'analyzer-source-slot'; const visible = document.createElement('input'); visible.type = 'checkbox'; visible.checked = this.state.visible[index] !== false; visible.setAttribute('aria-label', 'Source ' + (index + 1) + ' anzeigen'); const select = document.createElement('select'); select.className = 'inline-select'; select.setAttribute('aria-label', 'Source ' + (index + 1)); row.append(visible, document.createTextNode('S' + (index + 1)), select); this.sourceArea.append(row); visible.addEventListener('change', () => { this.state.visible[index] = visible.checked; this.saveState(); if (!this.paused) this.render(this.lastAnalysis); }); select.addEventListener('change', () => { this.state.sources[index] = select.value; this.saveState(); if (!this.paused) this.render(this.lastAnalysis); }); return { row, visible, select }; }); this.setSourceRegistry(this.sourceNames); this.pauseButton?.setAttribute('aria-pressed', 'false');
  }
  buildModeControl() {
    const area = this.panel?.querySelector('.analyzer-mode-area'); if (!area) return; area.replaceChildren();
    if (this.mode === 'gainReduction') this.addModeSelect(area, 'Processor', 'reductionTarget', [['Compressor', 'compressor'], ['Limiter', 'limiter']], () => { this.history.reduction = []; });
    if (this.mode === 'transient') this.addModeSelect(area, 'Envelope', 'envelopeTarget', [['Envelope Follower 1', 'envelope1'], ['Envelope Follower 2', 'envelope2']]);
  }
  addModeSelect(area, labelText, key, options, onChange = () => {}) { const label = document.createElement('label'); label.textContent = labelText; const select = document.createElement('select'); select.className = 'inline-select'; options.forEach(([text, value]) => select.add(new Option(text, value))); select.value = this.state[key]; select.addEventListener('change', () => { this.state[key] = select.value; onChange(); this.saveState(); }); label.append(select); area.append(label); }
  setSourceRegistry(names = []) { const available = [...new Set(names.filter(name => SOURCE_LABELS[name] || name))]; if (!available.length || (this.registryInitialized && available.join() === this.sourceNames.join())) return; this.registryInitialized = true; this.sourceNames = available; this.slots?.forEach((slot, index) => { const current = available.includes(this.state.sources[index]) ? this.state.sources[index] : available.includes('output') ? 'output' : available[0]; this.state.sources[index] = current; if (slot.select.options.length !== available.length || [...slot.select.options].some((option, i) => option.value !== available[i])) { slot.select.replaceChildren(); available.forEach(name => slot.select.add(new Option(SOURCE_LABELS[name] || name, name))); } slot.select.value = current; }); this.saveState(); }
  setMode(mode) { this.mode = VIEW_INFO[mode] ? mode : 'spectrum'; this.state.mode = this.mode; this.selector.value = this.mode; this.description.textContent = VIEW_INFO[this.mode]; this.buildModeControl(); this.saveState(); if (!this.paused) this.render(this.lastAnalysis); }
  setPaused(paused) { if (paused && this.lastAnalysis) this.lastAnalysis = structuredClone(this.lastAnalysis); this.paused = Boolean(paused); this.pauseButton.textContent = this.paused ? 'Play' : 'Pause'; this.pauseButton.setAttribute('aria-pressed', String(this.paused)); this.pauseButton.classList.toggle('active', this.paused); if (!this.paused) this.render(this.lastAnalysis); }
  setProcessingSettings(settings) { this.settings = settings; }
  setDynamics(metrics) { if (this.paused) return; this.metrics = { ...this.metrics, ...metrics }; }
  setModulationVisuals(value) { this.modulation = value; }
  getAnalysisSources() { return [...new Set(this.state.sources.filter((source, index) => this.state.visible[index] !== false && this.sourceNames.includes(source)))].slice(0, 6); }
  sourceLabel(source) { return SOURCE_LABELS[source] || source; }
  resize() { const width = Math.max(320, this.canvas.clientWidth || 820), height = Math.max(190, this.canvas.clientHeight || 250), ratio = Math.min(window.devicePixelRatio || 1, 2), pixelWidth = Math.round(width * ratio), pixelHeight = Math.round(height * ratio); if (this.canvas.width !== pixelWidth || this.canvas.height !== pixelHeight) { this.canvas.width = pixelWidth; this.canvas.height = pixelHeight; } this.width = width; this.height = height; this.context.setTransform(ratio, 0, 0, ratio, 0, 0); }
  render(analysis) {
    if (this.paused) return; this.lastAnalysis = analysis; this.resize(); const ctx = this.context; ctx.clearRect(0, 0, this.width, this.height); ctx.fillStyle = css('--visualizer-bg') || '#0d1116'; ctx.fillRect(0, 0, this.width, this.height);
    const data = this.lastAnalysis; if (!data?.sources?.length) return this.drawEmpty('Audio starten, um die Analyse zu sehen.'); const wanted = new Set(this.getAnalysisSources()), active = data.sources.filter(source => wanted.has(source.source)); if (!active.length) return this.drawEmpty('Mindestens eine Source aktivieren.');
    if (this.mode === 'waveform') this.drawWaveforms(active); else if (this.mode === 'spectrum') this.drawSpectra(active, data.sampleRate); else if (this.mode === 'spectrogram') this.drawSpectrogram(active[0], data.sampleRate); else if (this.mode === 'dynamics') this.drawDynamics(active[0]); else if (this.mode === 'gainReduction') this.drawGainReduction(); else if (this.mode === 'response') this.drawResponse(active[0], data.sampleRate); else this.drawTransient(active[0]);
  }
  drawEmpty(message) { const ctx = this.context; ctx.fillStyle = css('--text-secondary') || '#748190'; ctx.font = '13px system-ui, sans-serif'; ctx.textAlign = 'center'; ctx.fillText(message, this.width / 2, this.height / 2); ctx.textAlign = 'left'; }
  drawGrid(top, height, rows = 4) { const ctx = this.context; ctx.strokeStyle = css('--border') || '#26313b'; ctx.lineWidth = 1; for (let row = 0; row <= rows; row += 1) { const y = top + height * row / rows; ctx.beginPath(); ctx.moveTo(42, y + .5); ctx.lineTo(this.width - 18, y + .5); ctx.stroke(); } }
  drawLegend(items) { const ctx = this.context; ctx.font = '11px system-ui, sans-serif'; let x = 44; items.forEach(([label, color]) => { ctx.fillStyle = color; ctx.fillRect(x, 8, 12, 3); ctx.fillStyle = css('--text-secondary') || '#9aa7b4'; ctx.fillText(label, x + 17, 12); x += Math.max(76, ctx.measureText(label).width + 32); }); }
  drawWaveforms(items) { const top = 24, height = this.height - 54, palette = colors(); this.drawGrid(top, height, 4); items.forEach((item, index) => this.drawWave(item.time, palette[index], 1.2, top, height, index / Math.max(1, items.length) * .04)); this.drawLegend(items.map((item, index) => [this.sourceLabel(item.source), palette[index]])); }
  drawWave(data, color, lineWidth, top, height, offset = 0) { if (!data?.length) return; const ctx = this.context; ctx.beginPath(); ctx.strokeStyle = color; ctx.lineWidth = lineWidth; for (let index = 0; index < data.length; index += 1) { const x = 42 + (this.width - 60) * index / Math.max(1, data.length - 1), y = top + height * (.5 - (data[index] + offset) * .45); if (!index) ctx.moveTo(x, y); else ctx.lineTo(x, y); } ctx.stroke(); }
  drawSpectra(items, sampleRate) { const top = 26, height = this.height - 58, palette = colors(); this.drawSpectrumGrid(top, height, sampleRate); items.forEach((item, index) => this.drawSpectrumLine(item.frequency, sampleRate, palette[index], top, height)); this.drawLegend(items.map((item, index) => [this.sourceLabel(item.source), palette[index]])); }
  drawSpectrumGrid(top, height, sampleRate) { const ctx = this.context, max = Math.min(20000, sampleRate / 2), minLog = Math.log(20), maxLog = Math.log(max); this.drawGrid(top, height, 4); ctx.font = '10px system-ui, sans-serif'; ctx.fillStyle = css('--text-secondary') || '#748190'; [20, 100, 1000, 10000, max].forEach(f => { if (f >= sampleRate / 2) return; const x = 42 + (this.width - 60) * (Math.log(f) - minLog) / (maxLog - minLog); ctx.fillText(f >= 1000 ? (f / 1000).toFixed(f >= 10000 ? 0 : 1) + 'k' : String(f), x - 10, this.height - 17); ctx.strokeStyle = css('--border') || '#202a34'; ctx.beginPath(); ctx.moveTo(x + .5, top); ctx.lineTo(x + .5, top + height); ctx.stroke(); }); ctx.fillText('dBFS', 4, top + 4); }
  drawSpectrumLine(data, sampleRate, color, top, height) { if (!data?.length) return; const ctx = this.context, minLog = Math.log(20), maxLog = Math.log(Math.min(20000, sampleRate / 2)); ctx.beginPath(); ctx.strokeStyle = color; ctx.lineWidth = 1.4; let started = false; for (let index = 1; index < data.length; index += 1) { const f = index * sampleRate / (data.length * 2); if (f < 20 || f > Math.min(20000, sampleRate / 2)) continue; const x = 42 + (this.width - 60) * (Math.log(f) - minLog) / (maxLog - minLog), y = top + height * (1 - (clamp(data[index], -100, 0) + 100) / 100); if (!started) { ctx.moveTo(x, y); started = true; } else ctx.lineTo(x, y); } ctx.stroke(); }
  drawSpectrogram(item, sampleRate) {
    const width = Math.max(1, Math.floor(this.width - 60)), height = Math.max(1, Math.floor(this.height - 45));
    if (!this.spectrogramCanvas) this.spectrogramCanvas = document.createElement('canvas');
    const canvas = this.spectrogramCanvas;
    if (canvas.width !== width || canvas.height !== height || this.spectrogramSource !== item.source) {
      canvas.width = width; canvas.height = height; this.spectrogramSource = item.source;
    }
    const ctx = canvas.getContext('2d');
    ctx.drawImage(canvas, -1, 0); ctx.clearRect(width - 1, 0, 1, height);
    const [r, g, b] = hexRgb(colors()[0]), maxFrequency = Math.min(20000, sampleRate / 2);
    for (let y = 0; y < height; y++) {
      const frequency = 20 * (maxFrequency / 20) ** (1 - y / Math.max(1, height - 1));
      const index = clamp(Math.round(frequency / sampleRate * item.frequency.length * 2), 0, item.frequency.length - 1);
      const strength = clamp((item.frequency[index] + 94) / 86, 0, 1);
      ctx.fillStyle = 'rgba(' + r + ',' + g + ',' + b + ',' + (.06 + strength * .88) + ')';
      ctx.fillRect(width - 1, y, 1, 1);
    }
    this.context.drawImage(canvas, 42, 18, width, height);
    this.context.fillStyle = css('--text-secondary'); this.context.font = '12px system-ui';
    this.context.fillText('Zeit → · Frequenz logarithmisch ↑', 42, this.height - 10);
    this.drawLegend([[this.sourceLabel(item.source), colors()[0]]]);
  }
  drawDynamics(item) { const samples = item.time || []; let peak = 0, sum = 0; for (const value of samples) { const magnitude = Math.abs(value); peak = Math.max(peak, magnitude); sum += value * value; } const rms = Math.sqrt(sum / Math.max(1, samples.length)); this.push('peak', db(peak)); this.push('rms', db(rms)); const ctx = this.context; ctx.font = '13px system-ui, sans-serif'; [['Peak', db(peak), colors()[0]], ['RMS', db(rms), colors()[2]], ['Crest', db(peak) - db(rms), colors()[1]]].forEach(([label, value, color], index) => { const x = 44 + index * (this.width - 70) / 3; ctx.fillStyle = color; ctx.fillText(label, x, 28); ctx.fillStyle = css('--text-primary') || '#e9edf2'; ctx.font = '20px system-ui, sans-serif'; ctx.fillText(`${Number(value).toFixed(1)} dB${label === 'Crest' ? '' : 'FS'}`, x, 53); ctx.font = '13px system-ui, sans-serif'; }); const top = 76, height = this.height - 98; this.drawGrid(top, height, 4); this.drawHistory('peak', colors()[0], top, height, -80, 0); this.drawHistory('rms', colors()[2], top, height, -80, 0); this.drawLegend([['Peak', colors()[0]], ['RMS', colors()[2]], ['Crest Factor', colors()[1]]]); }
  drawGainReduction() { const value = Math.max(0, Number(this.metrics[this.state.reductionTarget]) || 0); this.push('reduction', value); const ctx = this.context, top = 34, height = this.height - 62; this.drawGrid(top, height, 4); ctx.fillStyle = css('--text-primary') || '#e9edf2'; ctx.font = '13px system-ui, sans-serif'; ctx.fillText(`${this.state.reductionTarget === 'limiter' ? 'Limiter' : 'Compressor'}: ${value.toFixed(1)} dB Reduction`, 42, 22); this.drawHistory('reduction', colors()[1], top, height, 24, 0); ctx.fillStyle = css('--text-secondary') || '#9aa7b4'; ctx.font = '10px system-ui, sans-serif'; [0, 6, 12, 18, 24].forEach(v => ctx.fillText(`${v} dB`, 5, top + height * v / 24 + 3)); }
  drawResponse(item, sampleRate) { const top = 26, height = this.height - 58; this.drawSpectrumGrid(top, height, sampleRate); this.drawSpectrumLine(item.frequency, sampleRate, colors()[0], top, height); const settings = this.settings; if (!settings) return this.drawLegend([[this.sourceLabel(item.source), colors()[0]]]); const ctx = this.context, max = Math.min(20000, sampleRate / 2), minLog = Math.log(20), maxLog = Math.log(max), x = f => 42 + (this.width - 60) * (Math.log(f) - minLog) / (maxLog - minLog), responseY = v => top + height * (1 - (clamp(v, -24, 12) + 24) / 36); const drawCurve = (color, calculator) => { ctx.beginPath(); ctx.strokeStyle = color; ctx.lineWidth = 1.7; for (let i = 0; i <= 320; i += 1) { const f = 20 * Math.pow(max / 20, i / 320), point = calculator(f), py = responseY(point); if (!i) ctx.moveTo(x(f), py); else ctx.lineTo(x(f), py); } ctx.stroke(); }; if (settings.filterEnabled) drawCurve(colors()[1], f => settings.filterType === 'allpass' ? 0 : filterResponseAt(settings.filterType, f, settings).value); if (settings.eqEnabled) drawCurve(colors()[2], f => eqResponseAt(f, settings)); ctx.fillStyle = css('--text-secondary') || '#9aa7b4'; ctx.font = '10px system-ui, sans-serif'; ctx.fillText('Response ± dB', 4, top + height / 2); this.drawLegend([[this.sourceLabel(item.source), colors()[0]], ['Filter', colors()[1]], ['EQ', colors()[2]]]); }
  drawTransient(item) { const samples = item.time || [], envelopeId = this.state.envelopeTarget, raw = this.modulation?.input || 0; this.push('input', raw); this.push(envelopeId, this.modulation?.envelope?.[envelopeId] || 0); const top = 26, height = this.height - 56; this.drawGrid(top, height, 4); this.drawUnitHistory('input', 'rgba(150,165,180,.75)', top, height); this.drawUnitHistory(envelopeId, colors()[2], top, height); this.drawLegend([['Input level', 'rgba(150,165,180,.75)'], [envelopeId === 'envelope2' ? 'Envelope Follower 2' : 'Envelope Follower 1', colors()[2]]]); }
  push(key, value) { const values = this.history[key]; values.push(Number.isFinite(value) ? value : 0); if (values.length > 180) values.shift(); }
  drawHistory(key, color, top, height, min, max) { const values = this.history[key], ctx = this.context; if (!values.length) return; ctx.strokeStyle = color; ctx.lineWidth = 1.7; ctx.beginPath(); values.forEach((value, index) => { const x = 42 + (this.width - 60) * index / Math.max(1, values.length - 1), y = top + height * (1 - clamp((value - min) / (max - min || 1), 0, 1)); if (!index) ctx.moveTo(x, y); else ctx.lineTo(x, y); }); ctx.stroke(); }
  dispose() { this.events.abort(); this.resizeObserver?.disconnect(); this.lastAnalysis = null; }
  drawUnitHistory(key, color, top, height) { const values = this.history[key], ctx = this.context; if (!values.length) return; ctx.strokeStyle = color; ctx.lineWidth = 1.7; ctx.beginPath(); values.forEach((value, index) => { const x = 42 + (this.width - 60) * index / Math.max(1, values.length - 1), y = top + height * (1 - clamp(value, 0, 1)); if (!index) ctx.moveTo(x, y); else ctx.lineTo(x, y); }); ctx.stroke(); }
}
